create database AcademyDB
use AcademyDB


CREATE TABLE Curators (
    Id INT PRIMARY KEY IDENTITY,
    Name VARCHAR(MAX) NOT NULL,
    Surname VARCHAR(MAX) NOT NULL
);

CREATE TABLE Faculties (
    Id INT PRIMARY KEY IDENTITY,
    Financing MONEY NOT NULL DEFAULT 0,
    Name VARCHAR(100) NOT NULL UNIQUE
);

CREATE TABLE Departments (
    Id INT PRIMARY KEY IDENTITY,
    Financing MONEY NOT NULL DEFAULT 0,
    Name VARCHAR(100) NOT NULL UNIQUE,
    FacultyId INT FOREIGN KEY REFERENCES Faculties(Id)
);

CREATE TABLE Groups (
    Id INT PRIMARY KEY IDENTITY,
    Name VARCHAR(10) NOT NULL UNIQUE,
    Year INT NOT NULL,
    DepartmentId INT FOREIGN KEY REFERENCES Departments(Id)
);

CREATE TABLE GroupsCurators (
    Id INT PRIMARY KEY IDENTITY,
    CuratorId INT FOREIGN KEY REFERENCES Curators(Id),
    GroupId INT FOREIGN KEY REFERENCES Groups(Id)
);

CREATE TABLE Lectures (
    Id INT PRIMARY KEY IDENTITY,
    LectureRoom VARCHAR(MAX) NOT NULL,
    SubjectId INT FOREIGN KEY REFERENCES Subjects(Id),
    TeacherId INT FOREIGN KEY REFERENCES Teachers(Id)
);

CREATE TABLE GroupsLectures (
    Id INT PRIMARY KEY IDENTITY,
    GroupId INT FOREIGN KEY REFERENCES Groups(Id),
    LectureId INT FOREIGN KEY REFERENCES Lectures(Id)
);

CREATE TABLE Subjects (
    Id INT PRIMARY KEY IDENTITY,
    Name VARCHAR(100) NOT NULL UNIQUE
);

CREATE TABLE Teachers (
    Id INT PRIMARY KEY IDENTITY,
    Name VARCHAR(MAX) NOT NULL,
    Salary MONEY NOT NULL,
    Surname VARCHAR(MAX) NOT NULL
);



